version: '3.8'

services:
  # Backend
  backend:
    build:
      context: .  # Caminho para o Dockerfile do backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: db  # SERVIÇO DB
      DB_USER: fatec
      DB_PASSWORD: fatec
      DB_NAME: salao_beleza
    depends_on:
      - db
    command: /bin/sh -c "until nc -z -v -w30 db 3306; do echo 'Aguardando DB...'; sleep 2; done; npm start"

  # Banco de dados MariaDB
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fatec
      MYSQL_DATABASE: salao_beleza
      MYSQL_USER: fatec
      MYSQL_PASSWORD: fatec
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  # Frontend Server 1
  frontend-server1:
    build:
      context: ../../5S_REDES_FRONTEND/frontend
    ports:
      - "8001:8001"
    volumes:
      - ../../5S_REDES_FRONTEND/frontend/nginx/nginx-server1.conf:/etc/nginx/nginx.conf  
    depends_on:
      - backend
      - db
    environment:
      VITE_BASE_URL: http://localhost:3000/api
      VITE_BASE_PATH_FRONTEND: http://localhost:8001
      VITE_FRONTEND_PORT: 8001
    command: /bin/sh -c "until nc -z -v -w30 db 3306; do echo 'Aguardando DB...'; sleep 2; done; until curl -s http://backend:3000/api/health; do echo 'Aguardando Backend...'; sleep 2; done; npm run dev --mode server1"

  # Frontend Server 2
  frontend-server2:
    build:
      context: ../../5S_REDES_FRONTEND/frontend
    ports:
      - "8002:8002"
    volumes:
      - ../../5S_REDES_FRONTEND/frontend/nginx/nginx-server2.conf:/etc/nginx/nginx.conf  
    depends_on:
      - backend
      - db
    environment:
      VITE_BASE_URL: http://localhost:3000/api
      VITE_BASE_PATH_FRONTEND: http://localhost:8002
      VITE_FRONTEND_PORT: 8002
    command: /bin/sh -c "until nc -z -v -w30 db 3306; do echo 'Aguardando DB...'; sleep 2; done; until curl -s http://backend:3000/api/health; do echo 'Aguardando Backend...'; sleep 2; done; npm run dev --mode server2"

  # Frontend Server 3
  frontend-server3:
    build:
      context: ../../5S_REDES_FRONTEND/frontend
    ports:
      - "8003:8003"
    volumes:
      - ../../5S_REDES_FRONTEND/frontend/nginx/nginx-server3.conf:/etc/nginx/nginx.conf  
    depends_on:
      - backend
      - db
    environment:
      VITE_BASE_URL: http://localhost:3000/api
      VITE_BASE_PATH_FRONTEND_SERVER3: http://localhost:8003
      VITE_FRONTEND_PORT: 8003
    command: /bin/sh -c "until nc -z -v -w30 db 3306; do echo 'Aguardando DB...'; sleep 2; done; until curl -s http://backend:3000/api/health; do echo 'Aguardando Backend...'; sleep 2; done; npm run dev --mode server3"
