version: '3.8'

services:
  backend:
    build:
      context: /home/thiago/code/5S_REDES_BACKEND/server
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - /home/thiago/code/5S_REDES_BACKEND/server:/usr/src/app
