version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: db  # SERVIÇO DB
      DB_USER: fatec
      DB_PASSWORD: fatec
      DB_NAME: salao_beleza
    depends_on:
      - db
    # Adiciona uma espera no serviço backend para garantir que o DB esteja pronto
    command: /bin/sh -c "until nc -z -v -w30 db 3306; do echo 'Aguardando DB...'; sleep 2; done; npm start"

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fatec
      MYSQL_DATABASE: salao_beleza
      MYSQL_USER: fatec
      MYSQL_PASSWORD: fatec
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  frontend:
    build:
      context: ../../5S_REDES_FRONTEND/frontend
    ports:
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
    depends_on:
      - backend
    environment:
      VITE_BASE_URL: http://localhost:3000/api
      VITE_BASE_PATH_FRONTEND_SERVER1: http://localhost:8001
      VITE_BASE_PATH_FRONTEND_SERVER2: http://localhost:8002
      VITE_BASE_PATH_FRONTEND_SERVER3: http://localhost:8003
    command: /bin/sh -c "until nc -z -v -w30 backend 3000; do echo 'Aguardando Backend...'; sleep 2; done; npm run start"
